### PR TITLE
Added sign_out translation to en.yml

### PR DESCRIPTION
**Pull request by jekuno**

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Where is this being referenced by devise?

**Comment by jekuno** [comment]
It's part of [devise docs](https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template) and e.g. also gets generated by the [RailsApps navigation generator](https://github.com/RailsApps/rails_layout/blob/master/lib/generators/layout/navigation/navigation_generator.rb).

**Comment by JasonBarnabe** [comment]
This gem right now only includes translations for Devise's views as they come out-of-the-box. If you're customizing the views and adding stuff, you'll have to add your own translations.

**Comment by jekuno** [comment]
Ok, thanks. I'll maintain those diffs separately then.

**Pull request closed without merging**
