### PR TITLE
slim_simple_form_foundation

### PR DESCRIPTION
**Pull request by yanyingwang**
rails generator: slim_simple_form_foundation

### CODE REVIEW

**Comment by allaire** [comment]
:+1:

**Comment by JasonBarnabe** [comment]
I'm not familiar with slim or foundation. Can you explain what this is, and why it belongs in this project?

**Comment by yanyingwang** [comment]
generally speaking, this is not necessary for a project doesn't bundle with [slim](https://github.com/slim-template/slim-rails) [simple_form](https://github.com/plataformatec/simple_form) and [foundation](https://github.com/zurb/foundation-rails) gems, but with them the default  devise view templates generated by `rails g devise:views:i18n_templates` will not be compatible. Actually I solve issue mcasimir/devise-i18n-views#64 in a way, and you can read the readme file part changed by me https://github.com/mcasimir/devise-i18n-views/pull/72/files.

**Comment by JasonBarnabe** [comment]
So these are alternate views, containing the same content and resulting in the same HTML, but in a different markup that matches that used when you have a combination of slim, simple_form, and foundation? The idea being that someone with that combination of gems would prefer to customize the views in this alternate format?

Is there something out there that creates devise views in this format *without* the i18n?

**Comment by JasonBarnabe** [comment]
This project is being merged into [devise-i18n](https://github.com/tigrish/devise-i18n). Please make all further contributions there.

**Pull request closed without merging**
